client/lib/client_web/router.ex
defmodule ClientWeb.Router do
  use ClientWeb, :router

  import ClientWeb.AuthController

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {ClientWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  # scope "/", ClientWeb do
  #   pipe_through :browser

  #   # get "/", PageController, :index
  #   get "/", SessionController
  # end

  scope "/", ClientWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/", SessionController, :new
    post "/", SessionController, :create
    get "/register", RegistrationController, :new
    post "/register", RegistrationController, :create
  end

  scope "/", ClientWeb do
    pipe_through [:browser, :require_authenticated_user]

    # Boards
    get "/new_board", NewBoardController, :new
    post "/new_board", NewBoardController, :create

    # Lists and Tasks
    live "/boards", BoardLive.Index, :index
    live "/boards/new", BoardLive.Index, :new

    # Lists
    live "/boards/:board_id/lists/:list_id", BoardLive.Index, :edit

    # Tasks
    live "/boards/:board_id/lists/:list_id/tasks/:task_id", BoardLive.Index, :edit

    live "/boards/:board_id/lists/:list_id/tasks/:task_id/index", TaskLive.Index, :index
    live "/boards/:board_id/lists/:list_id/tasks/:task_id/edit", TaskLive.Index, :edit

    # Comments
    live "/boards/:board_id/lists/:list_id/tasks/:task_id/comments", TaskLive.Index, :new

    live "/boards/:board_id/lists/:list_id/tasks/:task_id/comments/:comment_id",
         TaskLive.Index,
         :edit
  end

  scope "/", ClientWeb do
    pipe_through [:browser]

    delete "/logout", SessionController, :delete
  end

  # Other scopes may use custom stacks.
  # scope "/api", ClientWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  # if Mix.env() in [:dev, :test] do
  #   import Phoenix.LiveDashboard.Router

  #   scope "/" do
  #     pipe_through :browser

  #     live_dashboard "/dashboard", metrics: ClientWeb.Telemetry
  #   end
  # end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  # if Mix.env() == :dev do
  #   scope "/dev" do
  #     pipe_through :browser

  #     forward "/mailbox", Plug.Swoosh.MailboxPreview
  #   end
  # end
end

client/lib/client/sessions.ex
defmodule Client.Sessions do
  use Tesla

  # plug(Tesla.Middleware.BaseUrl, "http://localhost:4000/api")
  plug(Tesla.Middleware.BaseUrl, "http://172.20.0.4:4000/api")
  plug(Tesla.Middleware.JSON)

  def login(email, password) do
    with {:ok, response} <-
           post("/session", %{
             user: %{
               email: email,
               password: password
             }
           }) do
      case Map.has_key?(response.body, "data") do
        true ->
          {:ok, response.body["data"]}

        false ->
          {:error, response.body["error"]}
      end
    else
      {:error, reason} -> {:error, reason}
    end
  end

  def renew(renewal_token) do
    client = Tesla.client([{Tesla.Middleware.Headers, [{"authorization", renewal_token}]}])

    with {:ok, response} <- post(client, "/session/renew", %{}) do
      case Map.has_key?(response.body, "data") do
        true ->
          {:ok, response.body["data"]}

        false ->
          {:error, response.body["error"]}
      end
    else
      {:error, reason} -> {:error, reason}
    end
  end

  def logout(token) do
    client = Tesla.client([{Tesla.Middleware.Headers, [{"authorization", token}]}])

    with {:ok, response} <- delete(client, "/session") do
      case Map.has_key?(response.body, "data") do
        true ->
          {:ok, %{"message" => "User logged out."}}

        false ->
          {:error, response.body["error"]}
      end
    else
      {:error, reason} -> {:error, reason}
    end
  end
end

client/lib/client_web/controllers/session_controller.ex
defmodule ClientWeb.SessionController do
  use ClientWeb, :controller

  alias ClientWeb.AuthController

  alias Client.Sessions

  def new(conn, _params) do
    render(conn, "session.html", error_message: nil)
  end

  def create(conn, %{"user" => user_params}) do
    %{"email" => email, "password" => password} = user_params

    case Sessions.login(email, password) do
      {:ok, session_details} ->
        conn
        |> put_flash(:info, "User logged in successfully.")
        |> AuthController.log_in_user(session_details)

      # In order to prevent user enumeration attacks, don't disclose whether the email is registered.
      {:error, error} ->
        conn |> render("session.html", error_message: error["message"])
    end
  end

  def delete(conn, _params) do
    user_token = Plug.Conn.get_session(conn, :user_token)
    Sessions.logout(user_token)

    conn
    |> put_flash(:info, "User logged out successfully.")
    |> AuthController.log_out_user()
  end
end

client/lib/client_web/views/session_view.ex
defmodule ClientWeb.SessionView do
  use ClientWeb, :view
end

client/lib/client_web/templates/session/session.html.heex
<section class="mt-24 max-w-sm w-1/2 shadow flex flex-col items-center justify-center mx-auto p-6 bg-white">
  <h1 class="text-4xl font-bold italic text-gray-700">
    Login
  </h1>

  <.form let={f} for={:user} id="user-form" class="flex flex-col space-y-4 w-full px-6">

    <%= if @error_message do %>
    <div class="alert alert-danger text-center">
      <p><%= @error_message %></p>
    </div>
    <% end %>

    <div class="flex flex-col">
      <%= label f, :email, class: "text-gray-400" %>
      <%= email_input f, :email, autocomplete: "off", class: "rounded shadow-sm focus:ring-opacity-50 border-gray-300 focus:border-gray-900 focus:ring-gray-900" %>
      <%= error_tag f, :email %>
    </div>

    <div class="flex flex-col">
      <%= label f, :password, class: "text-gray-400" %>
      <%= password_input f, :password, class: "rounded shadow-sm focus:ring-opacity-50 border-gray-300 focus:border-gray-900 focus:ring-gray-900" %>
      <%= error_tag f, :password %>
    </div>

    <div>
      <%= submit "Log in", phx_disable_with: "Logging...", class: "w-full py-2 border-none shadow rounded font-semibold text-sm text-gray-50 hover:bg-sky-600 bg-sky-500" %>
    </div>

  </.form>

  <p class="text-sm px-10 text-center mt-6 text-gray-400 font-semibold">
    New here?
    <%= link "Sign up", to: Routes.registration_path(@conn, :new), class: "text-sky-500 hover:text-sky-600" %>
    and discover how this app can improve your productivity.
  </p>


</section>