client/lib/client_web/router.ex
defmodule ClientWeb.Router do
  use ClientWeb, :router

  import ClientWeb.AuthController

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {ClientWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  # scope "/", ClientWeb do
  #   pipe_through :browser

  #   # get "/", PageController, :index
  #   get "/", SessionController
  # end

  scope "/", ClientWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/", SessionController, :new
    post "/", SessionController, :create
    get "/register", RegistrationController, :new
    post "/register", RegistrationController, :create
  end

  scope "/", ClientWeb do
    pipe_through [:browser, :require_authenticated_user]

    # Boards
    get "/new_board", NewBoardController, :new
    post "/new_board", NewBoardController, :create

    # Lists and Tasks
    live "/boards", BoardLive.Index, :index
    live "/boards/new", BoardLive.Index, :new

    # Lists
    live "/boards/:board_id/lists/:list_id", BoardLive.Index, :edit

    # Tasks
    live "/boards/:board_id/lists/:list_id/tasks/:task_id", BoardLive.Index, :edit

    live "/boards/:board_id/lists/:list_id/tasks/:task_id/index", TaskLive.Index, :index
    live "/boards/:board_id/lists/:list_id/tasks/:task_id/edit", TaskLive.Index, :edit

    # Comments
    live "/boards/:board_id/lists/:list_id/tasks/:task_id/comments", TaskLive.Index, :new

    live "/boards/:board_id/lists/:list_id/tasks/:task_id/comments/:comment_id",
         TaskLive.Index,
         :edit
  end

  scope "/", ClientWeb do
    pipe_through [:browser]

    delete "/logout", SessionController, :delete
  end

  # Other scopes may use custom stacks.
  # scope "/api", ClientWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  # if Mix.env() in [:dev, :test] do
  #   import Phoenix.LiveDashboard.Router

  #   scope "/" do
  #     pipe_through :browser

  #     live_dashboard "/dashboard", metrics: ClientWeb.Telemetry
  #   end
  # end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  # if Mix.env() == :dev do
  #   scope "/dev" do
  #     pipe_through :browser

  #     forward "/mailbox", Plug.Swoosh.MailboxPreview
  #   end
  # end
end

client/lib/client_web/views/layout_view.ex
defmodule ClientWeb.LayoutView do
  use ClientWeb, :view

  # Phoenix LiveDashboard is available only in development by default,
  # so we instruct Elixir to not warn if the dashboard route is missing.
  @compile {:no_warn_undefined, {Routes, :live_dashboard_path, 2}}
end

client/lib/client_web/templates/layout/_user_menu.html.heex
<%= if @current_user do %>
<nav class="bg-white shadow-lg">
  <div class="mx-auto  py-4 px-4">
    <div class="flex justify-between">
      <!-- Primary Navbar items -->
      <div class="flex space-x-7">
        <%= if @boards == nil do %>
        <div class="flex items-center py-4 px-2">
          <span class="font-semibold text-sky-500 text-lg">Board++</span>
        </div>
        <% else %>
        <!-- Boards button -->
        <div class="relative group w-56 justify-right">
          <div
            class="py-2 border-none shadow rounded  font-semibold text-md text-gray-50 hover:bg-sky-600 bg-sky-500 flex items-center justify-center">
            <span class="mr-1">Boards</span>
            <svg class="fill-current h-5 w-4 align-middle" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
              <path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z" />
            </svg>
          </div>
          <div
            class="w-56 text-center items-center absolute rounded-b-md bg-white invisible group-hover:visible divide-y divide-sky-300">
            <div class="mx-4 px-2 py-4  font-medium text-gray-500 rounded transition duration-300 ">
              <%= link "New Board", to: Routes.new_board_path(@conn, :new)%>
            </div>
            <div>
              <%= for board <- @boards do %>
              <div id={"board-#{board.id}"}
                class="mx-4 px-2 py-4  font-medium text-gray-500 rounded transition duration-300">
                <%= link "#{board.title}", to: Routes.board_index_path(@conn, :index, id: board.id) %>
              </div>
              <% end %>
            </div>
          </div>
        </div>
        <% end %>
      </div>
      <!-- Secondary Navbar items -->
      <div class="hidden md:flex items-center space-x-3 ">
        <div class="relative group w-auto justify-right">
          <div class="py-2 px-2 font-medium rounded text-sky-500 transition duration-300">
            <%= @current_user.email %>
          </div>
          <div class="text-center items-center absolute rounded-b-md p-4 bg-white invisible group-hover:visible">
            <%= link "Log out", to: Routes.session_path(@conn, :delete), method: :delete, class: "mx-4 font-medium text-gray-500 rounded transition duration-300"%>
          </div>
        </div>
      </div>
      <!-- Mobile menu button -->
      <div class="md:hidden flex items-center">
        <button class="outline-none mobile-menu-button">
          <svg class="w-6 h-6 text-gray-500 hover:text-sky-500 " x-show="!showMenu" fill="none" stroke-linecap="round"
            stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" stroke="currentColor">
            <path d="M4 6h16M4 12h16M4 18h16"></path>
          </svg>
        </button>
      </div>
    </div>
  </div>
  <!-- mobile menu -->
  <div class="hidden mobile-menu">
    <ul>
      <li class="block text-md font-medium text-center px-2 py-4 text-sky-500 transition duration-300">
        <%= @current_user.email %>
      </li>
      <li
        class="block text-sm font-medium text-center text-gray-500 px-2 py-4 hover:bg-sky-500   hover:text-white transition duration-300">
        <%= link "Log out", to: Routes.session_path(@conn, :delete), method: :delete %>
      </li>
    </ul>
  </div>
</nav>
<% end %>

client/lib/client_web/templates/layout/app.html.heex
<main>
  <p class="alert alert-info text-center" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger text-center" role="alert"><%= get_flash(@conn, :error) %></p>
  <%= @inner_content %>
</main>

client/lib/client_web/templates/layout/live.html.heex
<main>
  <p class="alert alert-info text-center" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger text-center" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>

client/lib/client_web/templates/layout/root.html.heex
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <%= csrf_meta_tag() %>
  <%= live_title_tag assigns[:page_title] || "Client", suffix: " · Phoenix Framework" %>
  <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/assets/app.css" )} />
  <script defer phx-track-static type="text/javascript" src={Routes.static_path(@conn, "/assets/app.js" )}></script>
</head>

<body class="bg-sky-200">
  <%= render "_user_menu.html", assigns %>
  <%= @inner_content %>
</body>

</html>